//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Math {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Library {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Library() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Math.Library", typeof(Library).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to finish press &apos;escape&apos;.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to finish do not play games just push &apos;escape&apos;.
        /// </summary>
        internal static string exitHint {
            get {
                return ResourceManager.GetString("exitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What have you been up to?.
        /// </summary>
        internal static string greetings {
            get {
                return ResourceManager.GetString("greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To order lunch call 58 558 42 45. Ors sponsor Da Grasso pizzeria made the best pizza on these side of town. Do not hesitate call now..
        /// </summary>
        internal static string lunch {
            get {
                return ResourceManager.GetString("lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If you want to add numbers press &apos;A&apos;.
        /// </summary>
        internal static string optionAdding {
            get {
                return ResourceManager.GetString("optionAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If you want to divide numbers press &apos;D&apos;.
        /// </summary>
        internal static string optionDividing {
            get {
                return ResourceManager.GetString("optionDividing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You miss the key....
        /// </summary>
        internal static string optionException1 {
            get {
                return ResourceManager.GetString("optionException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did it again....
        /// </summary>
        internal static string optionException2 {
            get {
                return ResourceManager.GetString("optionException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If you want to order lunch press &apos;X&apos;.
        /// </summary>
        internal static string optionLunch {
            get {
                return ResourceManager.GetString("optionLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If you want to multiply numbers press &apos;M&apos;.
        /// </summary>
        internal static string optionMultiplication {
            get {
                return ResourceManager.GetString("optionMultiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - If you want to subtract numbers from each other press &apos;S&apos;.
        /// </summary>
        internal static string optionSubstraction {
            get {
                return ResourceManager.GetString("optionSubstraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
    }
}
